// Package core re-exports librobne/types as identical aliases (no convert loops).
package core

import libtypes "github.com/redhatinsights/ros-ocp-backend/librobne/types"

type WindowExtraOpts = libtypes.WindowExtraOpts
type WindowExtras = libtypes.WindowExtras
type ContainerExplanationFactors = libtypes.ContainerExplanationFactors
type GPUExplanationFactors = libtypes.GPUExplanationFactors
type NodeExplanationFactors = libtypes.NodeExplanationFactors
type PVCExplanationFactors = libtypes.PVCExplanationFactors
type QuotaExplanationFactors = libtypes.QuotaExplanationFactors
type ClusterQuotaExplanationFactors = libtypes.ClusterQuotaExplanationFactors
type VMExplanationFactors = libtypes.VMExplanationFactors
type SnapshotExplanationFactors = libtypes.SnapshotExplanationFactors
type NodeGPUTimeslicingExplanationFactors = libtypes.NodeGPUTimeslicingExplanationFactors
type IdleState = libtypes.IdleState
type IdleConfig = libtypes.IdleConfig
type IdleResult = libtypes.IdleResult
type NotificationThresholds = libtypes.NotificationThresholds
type NotificationCodeBitmap = libtypes.NotificationCodeBitmap
type ContainerKey = libtypes.ContainerKey
type RateCard = libtypes.RateCard
type NamespaceSpend = libtypes.NamespaceSpend
type DigestRow = libtypes.DigestRow
type CPURec = libtypes.CPURec
type MemoryRec = libtypes.MemoryRec
type ContainerRec = libtypes.ContainerRec
type TermConfig = libtypes.TermConfig
type CPUConfig = libtypes.CPUConfig
type MemoryConfig = libtypes.MemoryConfig
type SizingThresholdSettings = libtypes.SizingThresholdSettings
type KeyedDigest = libtypes.KeyedDigest
type EmitContainer = libtypes.EmitContainer
type EngineConfig = libtypes.EngineConfig

const (
	CategoryUndersized               = libtypes.CategoryUndersized
	CategoryOversized                = libtypes.CategoryOversized
	CategoryOptimized                = libtypes.CategoryOptimized
	CategoryThresholdPct             = libtypes.CategoryThresholdPct
	DefaultIdleThresholdMC           = libtypes.DefaultIdleThresholdMC
	DefaultIdleThresholdMemKiB       = libtypes.DefaultIdleThresholdMemKiB
	ContainerExplSQLColumns          = libtypes.ContainerExplSQLColumns
	ContainerExplUpdateSet           = libtypes.ContainerExplUpdateSet
	GPUExplUpdateSet                 = libtypes.GPUExplUpdateSet
	QuotaExplSQLColumns              = libtypes.QuotaExplSQLColumns
	QuotaExplUpdateSet               = libtypes.QuotaExplUpdateSet
	ClusterQuotaExplSQLColumns       = libtypes.ClusterQuotaExplSQLColumns
	ClusterQuotaExplUpdateSet        = libtypes.ClusterQuotaExplUpdateSet
	SnapshotExplSQLColumns           = libtypes.SnapshotExplSQLColumns
	SnapshotExplUpdateSet            = libtypes.SnapshotExplUpdateSet
	NodeGPUTimeslicingExplSQLColumns = libtypes.NodeGPUTimeslicingExplSQLColumns
	NodeGPUTimeslicingExplUpdateSet  = libtypes.NodeGPUTimeslicingExplUpdateSet
	VMExplSQLColumns                 = libtypes.VMExplSQLColumns
	VMExplUpdateSet                  = libtypes.VMExplUpdateSet
	IdleStateActive                  = libtypes.IdleStateActive
	IdleStateIdle                    = libtypes.IdleStateIdle
	IdleStateZombie                  = libtypes.IdleStateZombie
	MarginScale                      = libtypes.MarginScale
	NotifLowConfidence               = libtypes.NotifLowConfidence
	NotifStaleData                   = libtypes.NotifStaleData
	NotifOOMDetected                 = libtypes.NotifOOMDetected
	NotifPDBCaveat                   = libtypes.NotifPDBCaveat
	NotifIdleWorkload                = libtypes.NotifIdleWorkload
	NotifRecApplied                  = libtypes.NotifRecApplied
	NotifNewWorkload                 = libtypes.NotifNewWorkload
	NotifMemoryTrendingUp            = libtypes.NotifMemoryTrendingUp
	NotifGPUUnderutilized            = libtypes.NotifGPUUnderutilized
	NotifNodeUnderutilized           = libtypes.NotifNodeUnderutilized
	NotifNodeOvercommitted           = libtypes.NotifNodeOvercommitted
	NotifStrandedResources           = libtypes.NotifStrandedResources
	NotifASaturated                  = libtypes.NotifASaturated
	NotifNodeIdle                    = libtypes.NotifNodeIdle
	NotifAFlapping                   = libtypes.NotifAFlapping
	NotifARecommended                = libtypes.NotifARecommended
	NotifVMIdle                      = libtypes.NotifVMIdle
	NotifVMOversized                 = libtypes.NotifVMOversized
	NotifPVCOrphaned                 = libtypes.NotifPVCOrphaned
	NotifHPASaturated                = libtypes.NotifHPASaturated
	NotifHPAActive                   = libtypes.NotifHPAActive
	NotifInstanceNotInCat            = libtypes.NotifInstanceNotInCat
	NotifInstanceDeprecated          = libtypes.NotifInstanceDeprecated
	NotifNoCostData                  = libtypes.NotifNoCostData
	NotifGPUIdle                     = libtypes.NotifGPUIdle
	NotifGPUMemBound                 = libtypes.NotifGPUMemBound
	NotifGPUNoProfilingData          = libtypes.NotifGPUNoProfilingData
	NotifPVCOversized                = libtypes.NotifPVCOversized
	NotifPVCNearFull                 = libtypes.NotifPVCNearFull
	NotifSnapshotOrphaned            = libtypes.NotifSnapshotOrphaned
	NotifSnapshotNeverUsed           = libtypes.NotifSnapshotNeverUsed
	NotifSnapshotRedundant           = libtypes.NotifSnapshotRedundant
	NotifSnapshotStale               = libtypes.NotifSnapshotStale
	NotifSnapshotManaged             = libtypes.NotifSnapshotManaged
	NotifGPUTimeSharingCandidate     = libtypes.NotifGPUTimeSharingCandidate
	NotifQuotaNearCapacity           = libtypes.NotifQuotaNearCapacity
	NotifQuotaOversized              = libtypes.NotifQuotaOversized
	NotifQuotaBlocking               = libtypes.NotifQuotaBlocking
	NotifClusterQuotaAtCapacity      = libtypes.NotifClusterQuotaAtCapacity
	NotifNodePodSchedulingLimit      = libtypes.NotifNodePodSchedulingLimit
	NotifNodeFleetConsolidation      = libtypes.NotifNodeFleetConsolidation
	NotifSparseData                  = libtypes.NotifSparseData
	NotifGPUMultiDevice              = libtypes.NotifGPUMultiDevice
	NotifNodeBHNotPeakSafe           = libtypes.NotifNodeBHNotPeakSafe
	NotifGPUBHOfficeWindow           = libtypes.NotifGPUBHOfficeWindow
	MicroCentsPerDollar              = libtypes.MicroCentsPerDollar
	MicroCentsPerCent                = libtypes.MicroCentsPerCent
	MillicoresPerCore                = libtypes.MillicoresPerCore
	KiBPerGiB                        = libtypes.KiBPerGiB
	BytesPerGiB                      = libtypes.BytesPerGiB
	HoursPerMonthInt                 = libtypes.HoursPerMonthInt
)

var (
	ErrFieldsLocked                   = libtypes.ErrFieldsLocked
	ErrPartitionMissing               = libtypes.ErrPartitionMissing
	NullIfEmpty                       = libtypes.NullIfEmpty
	NullIfZeroInt64                   = libtypes.NullIfZeroInt64
	ClassifyResource                  = libtypes.ClassifyResource
	ClassifyOverall                   = libtypes.ClassifyOverall
	ComputeConfidence                 = libtypes.ComputeConfidence
	DecayWeight                       = libtypes.DecayWeight
	WeightedPercentile                = libtypes.WeightedPercentile
	MultiWeightedPercentile           = libtypes.MultiWeightedPercentile
	MultiWeightedPercentileWithExtras = libtypes.MultiWeightedPercentileWithExtras
	DeriveDecayHalfLifeHours          = libtypes.DeriveDecayHalfLifeHours
	DecayTableLookup                  = libtypes.DecayTableLookup
	LockedFieldsFromError             = libtypes.LockedFieldsFromError
	ContainerExplValuePlaceholders    = libtypes.ContainerExplValuePlaceholders
	AppendContainerExplArgs           = libtypes.AppendContainerExplArgs
	NullIntExpl                       = libtypes.NullIntExpl
	NullInt64Expl                     = libtypes.NullInt64Expl
	NullInt32Expl                     = libtypes.NullInt32Expl
	NullFloatExpl                     = libtypes.NullFloatExpl
	NullStringExpl                    = libtypes.NullStringExpl
	AppendGPUExplArgs                 = libtypes.AppendGPUExplArgs
	AppendQuotaExplArgs               = libtypes.AppendQuotaExplArgs
	AppendClusterQuotaExplArgs        = libtypes.AppendClusterQuotaExplArgs
	AppendSnapshotExplArgs            = libtypes.AppendSnapshotExplArgs
	AppendNodeGPUTimeslicingExplArgs  = libtypes.AppendNodeGPUTimeslicingExplArgs
	AppendVMExplArgs                  = libtypes.AppendVMExplArgs
	DefaultIdleConfig                 = libtypes.DefaultIdleConfig
	ClassifyIdleState                 = libtypes.ClassifyIdleState
	MaxDailyCPUUsageP95               = libtypes.MaxDailyCPUUsageP95
	MaxDailyMemUsageP95               = libtypes.MaxDailyMemUsageP95
	MaxCPU                            = libtypes.MaxCPU
	MaxMemBytes                       = libtypes.MaxMemBytes
	FindIdleSince                     = libtypes.FindIdleSince
	IsExcludedWorkloadType            = libtypes.IsExcludedWorkloadType
	IsExcludedNamespace               = libtypes.IsExcludedNamespace
	ComputeIdleDuration               = libtypes.ComputeIdleDuration
	CategoryFromIdleState             = libtypes.CategoryFromIdleState
	IdleStateForWrite                 = libtypes.IdleStateForWrite
	AllZeroUsage                      = libtypes.AllZeroUsage
	IdleClassificationAuthoritative   = libtypes.IdleClassificationAuthoritative
	SplitCSVList                      = libtypes.SplitCSVList
	ComputeAdaptiveMargin             = libtypes.ComputeAdaptiveMargin //nolint:staticcheck // identical alias of deprecated float wrapper
	ScaleMargin                       = libtypes.ScaleMargin
	ComputeAdaptiveMarginScaledDirect = libtypes.ComputeAdaptiveMarginScaledDirect
	ComputeAdaptiveMarginScaled       = libtypes.ComputeAdaptiveMarginScaled
	ApplyScaledMargin                 = libtypes.ApplyScaledMargin
	ScaleLimitMultiplier              = libtypes.ScaleLimitMultiplier
	ApplyOOMBumpScaled                = libtypes.ApplyOOMBumpScaled
	NotificationThresholdsFromSizing  = libtypes.NotificationThresholdsFromSizing
	NotificationCodesFromSlice        = libtypes.NotificationCodesFromSlice
	AppendUnique                      = libtypes.AppendUnique
	MergeNotificationCodes            = libtypes.MergeNotificationCodes
	SortedNotificationCodes           = libtypes.SortedNotificationCodes
	SelectCPUUsagePercentile          = libtypes.SelectCPUUsagePercentile
	SelectMemUsagePercentile          = libtypes.SelectMemUsagePercentile
	WithinTolerance                   = libtypes.WithinTolerance
	ComputeRecommendationAgeHours     = libtypes.ComputeRecommendationAgeHours
	IsPartitionMissing                = libtypes.IsPartitionMissing
	ComputeVariation                  = libtypes.ComputeVariation
	MaxWindowDays                     = libtypes.MaxWindowDays
	HoursInMonth                      = libtypes.HoursInMonth
	RateMicroCentsPerMCHour           = libtypes.RateMicroCentsPerMCHour
	RateMicroCentsPerGiBHour          = libtypes.RateMicroCentsPerGiBHour
	RateMicroCentsPerGiBMonth         = libtypes.RateMicroCentsPerGiBMonth
	RateMicroCentsPerDollarMonth      = libtypes.RateMicroCentsPerDollarMonth
	EffectiveRateMicroCentsPerMCHour  = libtypes.EffectiveRateMicroCentsPerMCHour
	EffectiveRateMicroCentsPerGiBHour = libtypes.EffectiveRateMicroCentsPerGiBHour
	EffectiveRateFromCPUTotals        = libtypes.EffectiveRateFromCPUTotals
	EffectiveRateFromMemTotals        = libtypes.EffectiveRateFromMemTotals
	CPUSavingsMicroCents              = libtypes.CPUSavingsMicroCents
	MemSavingsMicroCentsFromKiB       = libtypes.MemSavingsMicroCentsFromKiB
	GiBSavingsMicroCents              = libtypes.GiBSavingsMicroCents
	VCPUSavingsMicroCents             = libtypes.VCPUSavingsMicroCents
	MemorySavingsMicroCentsFromBytes  = libtypes.MemorySavingsMicroCentsFromBytes
	StorageSavingsMicroCentsFromBytes = libtypes.StorageSavingsMicroCentsFromBytes
	MonthlyFlatSavingsMicroCents      = libtypes.MonthlyFlatSavingsMicroCents
	MIGFractionSavingsMicroCents      = libtypes.MIGFractionSavingsMicroCents
	ScaleMicroCentsByBasisPoints      = libtypes.ScaleMicroCentsByBasisPoints
	MicroCentsToCents                 = libtypes.MicroCentsToCents
	MicroCentsToDollars               = libtypes.MicroCentsToDollars
	QuotaTightenSavingsMicroCents     = libtypes.QuotaTightenSavingsMicroCents
	ClampNonNegativeUSD               = libtypes.ClampNonNegativeUSD
	ReplicaCountInt                   = libtypes.ReplicaCountInt
	ReplicaCountForSavingsApply       = libtypes.ReplicaCountForSavingsApply
	ComputeTrendSlope                 = libtypes.ComputeTrendSlope
	CPUConfigFromSizing               = libtypes.CPUConfigFromSizing
	MemoryConfigFromSizing            = libtypes.MemoryConfigFromSizing
)
